<?php

namespace UseStoriesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * aRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aRepository extends EntityRepository
{
}
